### PR TITLE
add clap to benchmark binary

### PR DESCRIPTION
**Pull request by hardliner66**
This PR adds a clap interface for the benchmark tool and a common implementation to get seeds

### CODE REVIEW

**Comment by iMilchshake** [comment]
nice extension! is it possible to add some default to the Seed clap argument aswell?  I'd prefer to use a seed range from 0 to 100 unless specified otherwise.

**Comment by hardliner66** [comment]
I'm gonna do that today, but I think having it explicit would be beneficial for readability.

**Comment by hardliner66** [comment]
Done. I also added some help texts to make it clear what the options do.

**Comment by iMilchshake** [comment]
Thanks! Sadly it doesnt compile for me: I tried debug/release builds, `cargo clean` and `rustup update`.

```
error[E0599]: the method `clone` exists for enum `Option<Seeds>`, but its trait bounds were not satisfied
   --> src/bin/benchmark.rs:49:36
    |
49  |             let seeds = args.seeds.clone().unwrap_or_else(|| Seeds::Range {
    |                                    ^^^^^ method cannot be called on `Option<Seeds>` due to unsatisfied trait bounds
    |
   ::: /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/seed_gen-1.1.0/src/cli.rs:7:1
    |
7   | pub enum Seeds {
    | -------------- doesn't satisfy `Seeds: Clone`
    |
   ::: /home/tobi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:574:1
    |
574 | pub enum Option<T> {
    | ------------------ doesn't satisfy `Option<Seeds>: Clone`
    |
    = note: the following trait bounds were not satisfied:
            `Seeds: Clone`
            which is required by `Option<Seeds>: Clone`

For more information about this error, try `rustc --explain E0599`.
```

**Comment by hardliner66** [comment]
@iMilchshake upgrade your dependencies. Either delete your lock file and rebuild or do `cargo update`

**Comment by iMilchshake** [comment]
@hardliner66 can u publish 1.2 to crates.io?

**Comment by hardliner66** [comment]
Done

**Comment by iMilchshake** [comment]
thanks, now it works!

**Pull request merged**
